'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Universe
    Public Property Id As Integer
    Public Property Name As String
    Public Property CreatedBy As Integer
    Public Property CreatedDateUtc As Date
    Public Property ModifiedBy As Integer
    Public Property ModifiedDateUtc As Date

    Public Overridable Property SolarSystems As ICollection(Of SolarSystem) = New HashSet(Of SolarSystem)
    Public Overridable Property User As User
    Public Overridable Property User1 As User

End Class
