//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SqlDataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelestialObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CelestialObject()
        {
            this.CelestialObject1 = new HashSet<CelestialObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SolarSystemId { get; set; }
        public double Mass { get; set; }
        public double Radius { get; set; }
        public int TextureGroupId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> PrimaryId { get; set; }
        public Nullable<double> SemiMajorAxis { get; set; }
        public Nullable<double> Eccentricity { get; set; }
        public Nullable<double> Inclination { get; set; }
        public Nullable<double> ArgumentOfPeriapsis { get; set; }
        public Nullable<double> LongitudeOfAscendingNode { get; set; }
        public Nullable<double> MeanAnomalyZero { get; set; }
        public Nullable<int> RingSystemId { get; set; }
    
        public virtual CelestialObjectType CelestialObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CelestialObject> CelestialObject1 { get; set; }
        public virtual CelestialObject CelestialObject2 { get; set; }
        public virtual RingSystem RingSystem { get; set; }
        public virtual SolarSystem SolarSystem { get; set; }
        public virtual TextureGroup TextureGroup { get; set; }
    }
}
