'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RingSystem
    Public Property Id As Integer
    Public Property InnerRadius As Double
    Public Property OuterRadius As Double
    Public Property TextureGroupId As Integer

    Public Overridable Property CelestialObjects As ICollection(Of CelestialObject) = New HashSet(Of CelestialObject)
    Public Overridable Property TextureGroup As TextureGroup

End Class
