//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SqlDataProvider.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SolarSystemEntities : DbContext
    {
        public SolarSystemEntities()
            : base("name=SolarSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CelestialObject> CelestialObjects { get; set; }
        public virtual DbSet<CelestialObjectType> CelestialObjectTypes { get; set; }
        public virtual DbSet<RingSystem> RingSystems { get; set; }
        public virtual DbSet<SolarSystem> SolarSystems { get; set; }
        public virtual DbSet<Texture> Textures { get; set; }
        public virtual DbSet<TextureGroup> TextureGroups { get; set; }
        public virtual DbSet<TextureGroupToTexture> TextureGroupToTextures { get; set; }
        public virtual DbSet<TexturePath> TexturePaths { get; set; }
        public virtual DbSet<TextureQuality> TextureQualities { get; set; }
        public virtual DbSet<TextureType> TextureTypes { get; set; }
        public virtual DbSet<Universe> Universes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
