'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TextureGroupToTexture
    Public Property Id As Integer
    Public Property GroupId As Integer
    Public Property TextureId As Integer

    Public Overridable Property Texture As Texture
    Public Overridable Property TextureGroup As TextureGroup

End Class
