//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SqlDataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextureGroupToTexture
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int TextureId { get; set; }
    
        public virtual Texture Texture { get; set; }
        public virtual TextureGroup TextureGroup { get; set; }
    }
}
