//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SqlDataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Universe()
        {
            this.SolarSystems = new HashSet<SolarSystem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolarSystem> SolarSystems { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
